[build]
  command = "composer install"  # Comando para instalar dependencias PHP
  functions = "functions"       # Directorio que contiene funciones serverless (si las usas)
  publish = "public"            # Directorio público donde Netlify buscará archivos para servir

[context.production.environment]
  PHP_VERSION = "7.4"           # Configuración específica de entorno de producción

[context.deploy-preview.environment]
  PHP_VERSION = "7.4"           # Configuración específica de entorno para implementaciones de vista previa

[context.branch-deploy.environment]
  PHP_VERSION = "7.4"           # Configuración específica de entorno para implementaciones de rama